name: Render animation
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  renderGraph:
    name: Render animation
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: blah
          environment-file: environment.yaml
          python-version: 3.8
          condarc-file: .github/condarc
          auto-activate-base: false
      - run: |
          conda env list
          Rscript scripts/makeAnimation.R
          git diff
